def printer(schedule):

    print('######## 면접 스케줄 출력 결과 ########')
    print('21 (토) 1시 ~ 2시: ', end = '')
    print(schedule[0])
    print('21 (토) 2시 ~ 3시:', end = '')
    print(schedule[1])
    print('21 (토) 3시 ~ 4시:', end = '')
    print(schedule[2])
    print('21 (토) 4시 ~ 5시:', end = '')
    print(schedule[3])
    print('21 (토) 5시 ~ 6시:', end = '')
    print(schedule[4])
    print('22 (일) 1시 ~ 2시: ', end = '')
    print(schedule[5])
    print('22 (일) 2시 ~ 3시:', end = '')
    print(schedule[6])
    print('22 (일) 3시 ~ 4시:', end = '')
    print(schedule[7])
    print('22 (일) 4시 ~ 5시:', end = '')
    print(schedule[8])
    print('22 (일) 5시 ~ 6시:', end = '')
    print(schedule[9])
    print('23 (월) 6시 ~ 7시:', end = '')
    print(schedule[10])
    print('23 (월) 7시 ~ 8시:', end = '')
    print(schedule[11])
    print('23 (월) 8시 ~ 9시:', end = '')
    print(schedule[12])

if __name__ == "__main__":
	printer()